### ISSUE TITLE
Enable transparency on reversal-dark plasma theme

### ISSUE THREAD

**Issue by esskayesss** [yeyushengfan258/Reversal-kde#1]
I haven't seen such serenity in another theme and it's so close to being perfect according to me. 

Enhancement: Maybe you could consider adding some panel transparency to it.

I am not greatly experienced with tweaking plasma themes, but if there is a simple way to tweak it and add some transparency, please help me with it.

[This](https://askubuntu.com/questions/1173618/how-to-make-kde-plasma-taskbar-panel-transparent) didn't seem to work out.

**Comment by yeyushengfan258** [comment]
Thank you

I will upload a transparent configuration that you can choose to use.

**Comment by esskayesss** [comment]
Would be great! Can't wait to incorporate it :)

Kudos!
